"""Add is_favorite to clothing

Revision ID: 041ae00ae00a
Revises: 0a307d476a91
Create Date: 2026-04-07 23:08:42.656146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041ae00ae00a'
down_revision: Union[str, None] = '0a307d476a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing', 'is_favorite')
    # ### end Alembic commands ###