"""Add clothing model

Revision ID: 0a307d476a91
Revises: de51544b0269
Create Date: 2026-04-07 22:24:51.182695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a307d476a91'
down_revision: Union[str, None] = 'de51544b0269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('occasion', sa.JSON(), nullable=True),
    sa.Column('style_aesthetic', sa.JSON(), nullable=True),
    sa.Column('mood', sa.JSON(), nullable=True),
    sa.Column('time', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('specific_colors', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_id'), 'clothing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothing_id'), table_name='clothing')
    op.drop_table('clothing')
    # ### end Alembic commands ###