"""Add stylist picture field

Revision ID: 10daa6e656db
Revises: 9032eafe2bca
Create Date: 2026-04-09 23:32:41.892075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10daa6e656db'
down_revision: Union[str, None] = '9032eafe2bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stylist_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stylist_picture')
    # ### end Alembic commands ###