"""Add appearance analysis fields to user

Revision ID: 23e12d76af07
Revises: 291ea123f086
Create Date: 2026-04-09 20:28:09.402173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e12d76af07'
down_revision: Union[str, None] = '291ea123f086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('body_shape', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skin_tone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('color_palette', sa.String(), nullable=True))
    op.add_column('users', sa.Column('style_advice', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'style_advice')
    op.drop_column('users', 'color_palette')
    op.drop_column('users', 'skin_tone')
    op.drop_column('users', 'body_shape')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    # ### end Alembic commands ###