"""add saved_generated_outfits

Revision ID: 291ea123f086
Revises: 041ae00ae00a
Create Date: 2026-04-09 17:25:43.205374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291ea123f086'
down_revision: Union[str, None] = '041ae00ae00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saved_generated_outfits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'saved_generated_outfits')
    # ### end Alembic commands ###