"""Add sun and hair fields

Revision ID: 9032eafe2bca
Revises: 23e12d76af07
Create Date: 2026-04-09 21:19:00.391820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9032eafe2bca'
down_revision: Union[str, None] = '23e12d76af07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sun_reaction', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hair_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hair_color')
    op.drop_column('users', 'sun_reaction')
    # ### end Alembic commands ###