"""add_visual_embedding_to_clothing

Revision ID: c97df6341e02
Revises: ca891afe4509
Create Date: 2026-04-19 16:20:48.530796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97df6341e02'
down_revision: Union[str, None] = 'ca891afe4509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing', sa.Column('visual_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing', 'visual_embedding')
    # ### end Alembic commands ###