"""add personalized_mannequin to user

Revision ID: ca891afe4509
Revises: db24b5d42ad3
Create Date: 2026-04-11 14:40:32.897189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca891afe4509'
down_revision: Union[str, None] = 'db24b5d42ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personalized_mannequin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personalized_mannequin')
    # ### end Alembic commands ###