"""add wishlist to user

Revision ID: db24b5d42ad3
Revises: 10daa6e656db
Create Date: 2026-04-11 11:49:03.748696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db24b5d42ad3'
down_revision: Union[str, None] = '10daa6e656db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wishlist', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wishlist')
    # ### end Alembic commands ###