"""Add profile fields to user

Revision ID: de51544b0269
Revises: 27379153589b
Create Date: 2026-04-07 20:24:09.309346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de51544b0269'
down_revision: Union[str, None] = '27379153589b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('clothes_owned', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('fashion_inspo_board', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('best_outfits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'best_outfits')
    op.drop_column('users', 'fashion_inspo_board')
    op.drop_column('users', 'clothes_owned')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'age')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###